database:
  motosales:
    name: motosales
    port: 3306
dobo:
  mobo:
    nomo:
      master:
        paster:
           puppets: 
             metallica: guitar
              
    port: 3306
    tests:
      test2: 3
    test3: 23

d:
  m:
    n: 1234
    
